veeam/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
veeam/client.py,sha256=QqR0ZKu75XpnLtVbzc0SWo5cPPedDYSTN2hyWjaRY7A,8283
veeam/errors.py,sha256=Lie30vdP3_7iYrO6yOYL0qsIeJIvRTJCyqfRR7rEa2g,706
veeam-0.1.3.dist-info/METADATA,sha256=vr9ky_lA6ANq2BhTNz1Jo4FFI_1bNnkr9So5IPYDR0k,1880
veeam-0.1.3.dist-info/WHEEL,sha256=S8S5VL-stOTSZDYxHyf0KP7eds0J72qrK0Evu3TfyAY,92
veeam-0.1.3.dist-info/top_level.txt,sha256=DY6TIwTOXYMMO4tmKLVpJIftzgD5oExnlFA_voM569s,6
veeam-0.1.3.dist-info/RECORD,,
